[workspace]
resolver = "2" # 如果有 workspace, wgpu 需要在 workspace 指明 resolver = "2"

members = [
    "playground",
    "asynchronous",
    "my-redis",
    "socket",
    "system",
    "try-dioxus",
    "try-prost",
    "try-wgpu",
]
